project:
  type: website

execute:
  freeze: auto  # re-render only when source changes

website:
  title: "Data Science Concepts / Data Science Tools"
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
        
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Syllabus"
        file: index.qmd
      - text: "**Schedule**"
        file: schedule.qmd
      - text: "Homework"
        file: homework.qmd
      # - text: "Report writing"
        # file: reports.qmd
      - text: "Help"
        file: help.qmd
      - text: "Literature"
        file: literature.qmd
      - text: "Onboarding Late-arriving"
        file: late.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true



